version: "3.8"

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy  
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/start.sh && /app/start.sh"]

  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${SQL_NAME}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_NAME}"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
