apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: development
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: development
spec:
  ports:
  - port: 8000
  selector:
    app: web