name: Run Django Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

  

    - name: Build and Start Docker Compose Services
      working-directory: ./Kolokviumska
      run: |
        docker compose -f docker-compose.yml up -d --build

    - name: Wait for Database to Be Ready
      working-directory: ./Kolokviumska
      run: |
        until docker compose exec -T postgres pg_isready -h localhost -p 5432; do
          echo "Waiting for PostgreSQL to be ready..."
          sleep 2
        done

    - name: Run Django Tests
      working-directory: ./Kolokviumska
      run: |
        docker compose exec -T web python manage.py test

    - name: Stop Docker Compose Services
      working-directory: ./Kolokviumska
      run: docker compose down
